apiVersion: apps/v1
kind: Deployment
metadata:
  name:  log4j-app
spec:
  selector:
    matchLabels:
      app:  log4j-app
  template:
    metadata:
      labels:
        app:  log4j-app
    spec:
      containers:
        - name:  log4j-app
          image: imageName # IMPORTANT: Update!
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  log4j-app
  name:  log4j-app
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app:  log4j-app
