AWSTemplateFormatVersion: 2010-09-09
Description: Lacework EKS Audit Integration
Parameters:
  ExternalID:
    Description: >-
      The cross-account access role created by the stack will use this value for
      its ExternalID.
    Type: String
  ResourceNamePrefix:
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    Default: lwintawsimmersionday
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
Resources:
  LaceworkEKSSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks
  LaceworkEKSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Sid: AllowLaceworkToSubscribe
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - '434813966438'
                  - ':root'
            Action: 'sns:Subscribe'
            Resource:
              - !Ref LaceworkEKSSNSTopic
          - Sid: AllowS3ToPublish
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              - !Ref LaceworkEKSSNSTopic
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref 'AWS::AccountId'
              ArnLike:
                'aws:SourceArn': !Join
                  - ''
                  - - 'arn:aws:s3:*:*:'
                    - !Ref ResourceNamePrefix
                    - '-lacework-eks'
      Topics:
        - !Ref LaceworkEKSSNSTopic
  LaceworkEKSBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${AWS::AccountId}-laceworkeks-${ResourceNamePrefix}"
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref LaceworkEKSSNSTopic
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Join
                      - /
                      - - eks_audit_logs
                        - !Ref 'AWS::AccountId'
    DependsOn:
      - LaceworkEKSSNSTopic
      - LaceworkEKSTopicPolicy
  LaceworkEKSFirehose:
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      DeliveryStreamName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        RoleARN: !GetAtt
          - LaceworkEKSFirehoseIAMRole
          - Arn
        BucketARN: !GetAtt
          - LaceworkEKSBucket
          - Arn
        Prefix: !Join
          - ''
          - - eks_audit_logs/
            - !Ref 'AWS::AccountId'
            - /
        ErrorOutputPrefix: !Join
          - ''
          - - audit_logs/
            - !Ref 'AWS::AccountId'
            - /error/
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 100
        CloudWatchLoggingOptions:
          Enabled: 'false'
        CompressionFormat: UNCOMPRESSED
        EncryptionConfiguration:
          NoEncryptionConfig: NoEncryption
    DependsOn:
      - LaceworkEKSBucket
      - LaceworkFirehoseIAMPolicy
  LaceworkEKSFirehoseIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-fh-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
  LaceworkFirehoseIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-fh-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !Join
                - /
                - - !GetAtt
                    - LaceworkEKSBucket
                    - Arn
                  - '*'
      Roles:
        - !Ref LaceworkEKSFirehoseIAMRole
  LaceworkEKSCrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-ca-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - '434813966438'
                  - ':root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalID
  LaceworkCrossAccountPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-ca-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3Permissions
            Action:
              - 's3:Get*'
              - 's3:ListBucket'
              - 's3:ListObjectsV2'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ResourceNamePrefix
                  - '-lacework-eks'
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ResourceNamePrefix
                  - '-lacework-eks'
                  - /*
          - Sid: CloudWatchLogsPermissions
            Action:
              - 'logs:DescribeSubscriptionFilters'
              - 'logs:PutSubscriptionFilter'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:logs:'
                - !Ref 'AWS::Region'
                - ':'
                - !Ref 'AWS::AccountId'
                - ':log-group:/aws/eks/*:*'
          - Sid: IAMPermissions
            Effect: Allow
            Action:
              - 'iam:GetRole'
              - 'iam:PassRole'
            Resource: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref 'AWS::AccountId'
                - ':role/*lacework-eks-cw*'
          - Sid: SNSPermissions
            Action:
              - 'sns:GetTopicAttributes'
              - 'sns:Subscribe'
              - 'sns:Unsubscribe'
            Effect: Allow
            Resource: !Ref LaceworkEKSSNSTopic
          - Sid: FirehosePermissions
            Action:
              - 'firehose:DescribeDeliveryStream'
            Effect: Allow
            Resource: !GetAtt
              - LaceworkEKSFirehose
              - Arn
          - Sid: AccountAliasPermissions
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - Sid: DebugPermissions
            Action:
              - 'eks:ListClusters'
              - 'logs:DescribeLogGroups'
              - 'firehose:ListDeliveryStreams'
              - 'sns:ListTopics'
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketAcl'
              - 's3:GetBucketLocation'
              - 's3:GetBucketNotificationConfiguration'
              - 'cloudwatch:GetMetricData'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkEKSCrossAccountRole
  LaceworkSnsCustomResource:
    Type: 'Custom::LaceworkSnsCustomResource'
    DependsOn:
      - LaceworkEKSSNSTopic
      - LaceworkEKSBucket
      - LaceworkEKSFirehose
      - LaceworkEKSCrossAccountRole
    Properties:
      Type: AWS_EKS_AUDIT
      ServiceToken: !Join
        - ''
        - - 'arn:aws:sns:'
          - !Ref 'AWS::Region'
          - ':434813966438:prodn-customer-cloudformation'
      IntegrationName: !Ref 'AWS::StackName'
      RoleArn: !GetAtt
        - LaceworkEKSCrossAccountRole
        - Arn
      ExternalId: !Ref ExternalID
      SNSTopicArn: !Ref LaceworkEKSSNSTopic
      ApiToken: "{{resolve:ssm:AccessToken}}"
      Account: !Ref ResourceNamePrefix
      TemplateVersion: '1.1'
      AWSAccountId: !Ref 'AWS::AccountId'
Outputs:
  RoleARN:
    Description: >-
      Cross-account access role ARN to share with Lacework for EKS K8s
      integration
    Value: !GetAtt
      - LaceworkEKSCrossAccountRole
      - Arn
  ExternalID:
    Description: ExternalID to share with Lacework for EKS K8s integration
    Value: !Ref ExternalID
  SNSTopicArn:
    Description: SNS topic ARN to share with Lacework for EKS K8s integration
    Value: !Ref LaceworkEKSSNSTopic
  LaceworkEKSFirehoseArn:
    Description: >-
      Firehose Delivery Stream ARN to be used as destination by EKS CloudWatch
      Log group Subscription filter.
    Value: !GetAtt
      - LaceworkEKSFirehose
      - Arn
  TemplateVersion:
    Description: Template version
    Value: '1.1'
