AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS CloudTrail and Config Security Audit Integration
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Parameters:
          - ResourceNamePrefix
          - ExternalID
          - CreateTrail
      - Label:
          default: New Trail Options
        Parameters:
          - NewTrailLogFilePrefix
      - Label:
          default: Existing Trail Setup
        Parameters:
          - ExistingTrailBucketName
          - ExistingTrailTopicArn
    ParameterLabels:
      ResourceNamePrefix:
        default: Resource name prefix
      ExternalID:
        default: ExternalID
      CreateTrail:
        default: Create new trail?
      NewTrailLogFilePrefix:
        default: Log file prefix
      ExistingTrailBucketName:
        default: Bucket name
      ExistingTrailTopicArn:
        default: Topic ARN
Parameters:
  ResourceNamePrefix:
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    Default: lwintawsimmersionday
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExternalID:
    Description: >-
      The cross-account access role created by the stack will use this value for
      its ExternalID.
    Type: String
    Default: 2D1C019
    MinLength: '2'
    MaxLength: '1224'
  CreateTrail:
    Description: >-
      You can have a new multi-region CloudTrail trail be created (along with a
      new S3 bucket and SNS topic), or use your existing trail setup.
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  NewTrailLogFilePrefix:
    Description: >-
      If you want the new trail to prefix its log file names, provide the prefix
      to use.  Otherwise, leave it blank.
    Default: ''
    Type: String
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z0-9-_.!()* ]*'
    ConstraintDescription: 'Invalid log file prefix.  Must match pattern [a-zA-Z0-9-_.!()* ]*'
  ExistingTrailBucketName:
    Description: >-
      Provide the name of the S3 bucket for your existing trail setup.  The
      bucket must be owned by the current account.
    Default: ''
    Type: String
    MaxLength: '128'
  ExistingTrailTopicArn:
    Description: Provide the ARN of the SNS topic for your existing trail setup.
    Default: ''
    Type: String
    MaxLength: '256'
Conditions:
  CreateNewTrail: !Equals
    - !Ref CreateTrail
    - 'Yes'
  UseExistingTrail: !Not
    - !Equals
      - !Ref CreateTrail
      - 'Yes'
  NewTrailUsesLogFilePrefix: !Not
    - !Equals
      - !Ref NewTrailLogFilePrefix
      - ''
Resources:
  LaceworkCWSBucket:
    Condition: CreateNewTrail
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws-3c86'
  LaceworkCWSBucketPolicy:
    Condition: CreateNewTrail
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref LaceworkCWSBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: LaceworkCWSBucketPolicy
        Statement:
          - Sid: CloudTrailAclCheck
            Action: 's3:GetBucketAcl'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LaceworkCWSBucket
            Principal:
              Service: cloudtrail.amazonaws.com
          - Sid: CloudTrailWrite
            Action: 's3:PutObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LaceworkCWSBucket
                - !If
                  - NewTrailUsesLogFilePrefix
                  - !Join
                    - ''
                    - - /
                      - !Ref NewTrailLogFilePrefix
                  - ''
                - /AWSLogs/
                - !Ref 'AWS::AccountId'
                - /*
            Principal:
              Service: cloudtrail.amazonaws.com
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
              Bool:
                'aws:SecureTransport': 'true'
  LaceworkCWSTopic:
    Condition: CreateNewTrail
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws'
  LaceworkCWSTopicPolicy:
    Condition: CreateNewTrail
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudTrailPublish
            Action: 'SNS:Publish'
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Resource: '*'
      Topics:
        - !Ref LaceworkCWSTopic
  LaceworkCWSTrail:
    Condition: CreateNewTrail
    Type: 'AWS::CloudTrail::Trail'
    DependsOn:
      - LaceworkCWSTopicPolicy
      - LaceworkCWSBucketPolicy
    Properties:
      TrailName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws'
      S3BucketName: !Ref LaceworkCWSBucket
      S3KeyPrefix: !If
        - NewTrailUsesLogFilePrefix
        - !Ref NewTrailLogFilePrefix
        - !Ref 'AWS::NoValue'
      SnsTopicName: !GetAtt
        - LaceworkCWSTopic
        - TopicName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      IsLogging: true
  LaceworkCWSQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcws'
  LaceworkCWSQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AwsSnsAccess
            Effect: Allow
            Principal: '*'
            Action:
              - 'sqs:SendMessage'
            Resource: '*'
            Condition:
              ArnEquals:
                'aws:SourceArn': !If
                  - CreateNewTrail
                  - !Ref LaceworkCWSTopic
                  - !Ref ExistingTrailTopicArn
      Queues:
        - !Ref LaceworkCWSQueue
  LaceworkCWSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: !GetAtt
        - LaceworkCWSQueue
        - Arn
      Protocol: sqs
      TopicArn: !If
        - CreateNewTrail
        - !Ref LaceworkCWSTopic
        - !Ref ExistingTrailTopicArn
  LaceworkCWSSACrossAccountAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - ''
        - - !Ref ResourceNamePrefix
          - '-laceworkcwssarole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - '434813966438'
                  - ':root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalID
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
  LaceworkCWSPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: LaceworkCWSPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ConsumeNotifications
            Action:
              - 'sqs:GetQueueAttributes'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessage'
              - 'sqs:ReceiveMessage'
            Effect: Allow
            Resource:
              - !GetAtt
                - LaceworkCWSQueue
                - Arn
          - Sid: ListLogFiles
            Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !If
                    - UseExistingTrail
                    - !Ref ExistingTrailBucketName
                    - !Ref LaceworkCWSBucket
                  - /*AWSLogs/
            Condition:
              StringLike:
                's3:prefix':
                  - '*AWSLogs/'
          - Sid: ReadLogFiles
            Action:
              - 's3:Get*'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !If
                    - UseExistingTrail
                    - !Ref ExistingTrailBucketName
                    - !Ref LaceworkCWSBucket
                  - /*AWSLogs/*
          - Sid: GetAccountAlias
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - Sid: Debug
            Action:
              - 'cloudtrail:DescribeTrails'
              - 'cloudtrail:GetTrailTopics'
              - 'cloudtrail:GetTrailStatus'
              - 'cloudtrail:ListPublicKeys'
              - 'ec2:GetEbsEncryptionByDefault'
              - 's3:GetBucketAcl'
              - 's3:GetBucketPolicy'
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
              - 's3:GetBucketLogging'
              - 'sns:GetSubscriptionAttributes'
              - 'sns:GetTopicAttributes'
              - 'sns:ListSubscriptions'
              - 'sns:ListSubscriptionsByTopic'
              - 'sns:ListTopics'
            Effect: Allow
            Resource: '*'
      Roles:
        - !Ref LaceworkCWSSACrossAccountAccessRole
  LaceworkSnsCustomResource:
    Type: 'Custom::LaceworkSnsCustomResource'
    DependsOn:
      - LaceworkCWSPolicy
      - LaceworkCWSSACrossAccountAccessRole
      - LaceworkCWSQueuePolicy
      - LaceworkCWSQueue
    Properties:
      Type: AWS_CT_CFG
      ServiceToken: !Join
        - ''
        - - 'arn:aws:sns:'
          - !Ref 'AWS::Region'
          - ':434813966438:prodn-customer-cloudformation'
      IntegrationName: !Ref 'AWS::StackName'
      RoleArn: !GetAtt
        - LaceworkCWSSACrossAccountAccessRole
        - Arn
      ExternalId: !Ref ExternalID
      SqsQueueUrl: !Ref LaceworkCWSQueue
      ApiToken: "{{resolve:ssm:AccessToken}}"
      Account: !Ref ResourceNamePrefix
      TemplateVersion: '1.1'
      AWSAccountId: !Ref 'AWS::AccountId'
Outputs:
  RoleARN:
    Description: >-
      Cross-account access role ARN to share with Lacework for CloudTrail
      integration
    Value: !GetAtt
      - LaceworkCWSSACrossAccountAccessRole
      - Arn
  ExternalID:
    Description: ExternalID to share with Lacework for CloudTrail integration
    Value: !Ref ExternalID
  SQSQueueURL:
    Description: SQS queue URL to share with Lacework for CloudTrail Integration
    Value: !Ref LaceworkCWSQueue
  TemplateVersion:
    Description: Template version
    Value: '1.1'
