AWSTemplateFormatVersion: 2010-09-09
Description: Lacework AWS EKS Audit Log Integration
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Parameters:
          - ResourceNamePrefix
          - ExternalID
      - Label:
          default: Existing Bucket ARN
        Parameters:
          - ExistingBucketArn
    ParameterLabels:
      ResourceNamePrefix:
        default: Resource name prefix
      ExternalID:
        default: ExternalID
      ExistingBucketArn:
        default: Existing Bucket ARN
Parameters:
  ExternalID:
    Description: >-
      The cross-account access role created by the stack will use this value for
      its ExternalID.
    Type: String
  ResourceNamePrefix:
    Description: >-
      Names of resources created by the stack will be prefixed with this value
      to ensure uniqueness.
    Type: String
    Default: laceworkshop
    MinLength: '1'
    MaxLength: '45'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: >-
      Invalid resource name prefix value.  Must match pattern
      ^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$
  ExistingBucketArn:
    Description: >-
      Provide the ARN of the existing S3 bucket.  The bucket must be owned by
      the current account. If left blank an S3 Bucket will be created for you
      (optional)
    Default: ''
    Type: String
    MaxLength: '128'
  AllowDebuggingPermissions:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: 'To allow debugging permissions, set this parameter to true'
    Type: String
Conditions:
  CreateNewBucket: !Equals
    - !Ref ExistingBucketArn
    - ''
  AllowDebuggingPermissionsCondition: !Equals
    - !Ref AllowDebuggingPermissions
    - 'true'
Resources:
  LaceworkEKSSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks
  LaceworkEKSTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Sid: AllowLaceworkToSubscribe
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::434813966438:role/lacework-platform'
            Action: 'sns:Subscribe'
            Resource:
              - !Ref LaceworkEKSSNSTopic
          - Sid: AllowS3ToPublish
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              - !Ref LaceworkEKSSNSTopic
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref 'AWS::AccountId'
              ArnLike:
                'aws:SourceArn': !Join
                  - ''
                  - - 'arn:aws:s3:*:*:'
                    - !Ref AWS::AccountId
                    - '-lacework-eks-'
                    - !Ref ResourceNamePrefix
                    - '-'
                    - !Join ['',['lw',!Select [ 0, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ] ] ]
      Topics:
        - !Ref LaceworkEKSSNSTopic
  LaceworkEKSBucket:
    Condition: CreateNewBucket
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: !Join
        - '-'
        - - !Ref AWS::AccountId
          - 'lacework-eks'
          - !Ref ResourceNamePrefix
          - !Join ['',['lw',!Select [ 0, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ] ] ]
      NotificationConfiguration:
        TopicConfigurations:
          - Topic: !Ref LaceworkEKSSNSTopic
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: !Join
                      - /
                      - - eks_audit_logs
                        - !Ref 'AWS::AccountId'
    DependsOn:
      - LaceworkEKSSNSTopic
      - LaceworkEKSTopicPolicy
  LaceworkEKSFirehose:
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      DeliveryStreamName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        RoleARN: !GetAtt
          - LaceworkEKSFirehoseIAMRole
          - Arn
        BucketARN: !If
          - CreateNewBucket
          - !GetAtt
            - LaceworkEKSBucket
            - Arn
          - !Ref ExistingBucketArn
        Prefix: !Join
          - ''
          - - eks_audit_logs/
            - !Ref 'AWS::AccountId'
            - /
        ErrorOutputPrefix: !Join
          - ''
          - - audit_logs/
            - !Ref 'AWS::AccountId'
            - /error/
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 100
        CloudWatchLoggingOptions:
          Enabled: 'false'
        CompressionFormat: UNCOMPRESSED
        EncryptionConfiguration:
          NoEncryptionConfig: NoEncryption
    DependsOn:
      - LaceworkFirehoseIAMPolicy
  LaceworkEKSFirehoseIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-fh-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
  LaceworkFirehoseIAMPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-fh-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:PutObject'
            Resource:
              - !Join
                - ''
                - - !If
                    - CreateNewBucket
                    - !GetAtt
                      - LaceworkEKSBucket
                      - Arn
                    - !Ref ExistingBucketArn
                  - /eks_audit_logs/
                  - !Ref 'AWS::AccountId'
                  - '*'
      Roles:
        - !Ref LaceworkEKSFirehoseIAMRole
  LaceworkEKSCrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-ca-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::434813966438:role/lacework-platform'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalID
  LaceworkCrossAccountPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join
        - '-'
        - - !Ref ResourceNamePrefix
          - lacework-eks-ca-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: S3Permissions
            Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !If
              - CreateNewBucket
              - - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref ResourceNamePrefix
                    - '-lacework-eks-'
                    - !Join ['',['lw',!Select [ 0, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ] ] ]
                - !Join
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref ResourceNamePrefix
                    - '-lacework-eks-'
                    - !Join ['',['lw',!Select [ 0, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ] ] ]
                    - /*
              - - !Ref ExistingBucketArn
                - !Join
                  - ''
                  - - !Ref ExistingBucketArn
                    - /*
          - Sid: SNSPermissions
            Action:
              - 'sns:GetTopicAttributes'
              - 'sns:Subscribe'
              - 'sns:Unsubscribe'
            Effect: Allow
            Resource: !Ref LaceworkEKSSNSTopic
          - Sid: AccountAliasPermissions
            Action:
              - 'iam:ListAccountAliases'
            Effect: Allow
            Resource: '*'
          - !If
            - AllowDebuggingPermissionsCondition
            - Sid: DebugPermissions
              Action:
                - 'eks:ListClusters'
                - 'logs:DescribeLogGroups'
                - 'logs:DescribeSubscriptionFilters'
                - 'firehose:ListDeliveryStreams'
                - 'firehose:DescribeDeliveryStream'
              Effect: Allow
              Resource: '*'
            - !Ref 'AWS::NoValue'
          - !If
            - AllowDebuggingPermissionsCondition
            - Sid: S3DebugPermissions
              Action:
                - 's3:GetBucketAcl'
                - 's3:GetBucketLocation'
                - 's3:GetBucketNotificationConfiguration'
              Effect: Allow
              Resource: !If
                - CreateNewBucket
                - !GetAtt
                  - LaceworkEKSBucket
                  - Arn
                - !Ref ExistingBucketArn
            - !Ref 'AWS::NoValue'
      Roles:
        - !Ref LaceworkEKSCrossAccountRole
#  LaceworkSnsCustomResource:
#    Type: 'Custom::LaceworkSnsCustomResource'
#    DependsOn:
#      - LaceworkEKSSNSTopic
#      - LaceworkEKSFirehose
#      - LaceworkEKSCrossAccountRole
#    Properties:
#      Type: AWS_EKS_AUDIT
#      ServiceToken: !Join
#        - ''
#        - - 'arn:aws:sns:'
#          - !Ref 'AWS::Region'
#          - ':434813966438:prodn-customer-cloudformation'
#      IntegrationName: !Ref 'AWS::StackName'
#      RoleArn: !GetAtt
#        - LaceworkEKSCrossAccountRole
#        - Arn
#      ExternalId: !Ref ExternalID
#      SNSTopicArn: !Ref LaceworkEKSSNSTopic
#      ApiToken: '{{resolve:ssm:ACCESS_TOKEN}}'
#      Account: laceworkshop
#      S3BucketArn: !If
#        - CreateNewBucket
#        - !GetAtt
#          - LaceworkEKSBucket
#          - Arn
#        - !Ref ExistingBucketArn
#      TemplateVersion: '1.1'
#      AWSAccountId: !Ref 'AWS::AccountId'
Outputs:
  RoleARN:
    Description: >-
      Cross-account access role ARN to share with Lacework for EKS K8s
      integration
    Value: !GetAtt
      - LaceworkEKSCrossAccountRole
      - Arn
  ExternalID:
    Description: ExternalID to share with Lacework for EKS K8s integration
    Value: !Ref ExternalID
  SNSTopicArn:
    Description: SNS topic ARN to share with Lacework for EKS K8s integration
    Value: !Ref LaceworkEKSSNSTopic
  LaceworkEKSFirehoseArn:
    Description: >-
      Firehose Delivery Stream ARN to be used as destination by EKS CloudWatch
      Log group Subscription filter.
    Value: !GetAtt
      - LaceworkEKSFirehose
      - Arn
  S3BucketArn:
    Description: S3 Bucket ARN to store EKS Audit Logs
    Value: !If
      - CreateNewBucket
      - !GetAtt
        - LaceworkEKSBucket
        - Arn
      - !Ref ExistingBucketArn
  TemplateVersion:
    Description: Template version
    Value: '1.1'
