AWSTemplateFormatVersion: 2010-09-09
Description: "Set up AWS DevSecOps Pipeline with CodePipeline, CodeBuild, ECR & EKS and secure with Lacework."
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Basic Configuration"
        Parameters:
          - LaceworkAccountName
          - LaceworkAccessKeyID
          - LaceworkSecretKey
      - Label:
          default: "Advanced Configuration"
        Parameters:
          - S3BucketName
          - S3KeyPrefix
    ParameterLabels:
      LaceworkAccountName:
        default: Lacework Account Name
      LaceworkAccessKeyID:
        default: Lacework Access Key ID
      LaceworkSecretKey:
        default: Lacework Secret Key
      S3BucketName:
        default: CloudFormation S3 Bucket
      S3KeyPrefix:
        default: CloudFormation S3 Key Prefix

Parameters:
  LaceworkAccountName:
    Default: laceworkshop
    Type: String
    Description: Your Lacework account name. ie. <account name>.lacework.net
    MinLength: '1'
    AllowedPattern: '^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$'
    ConstraintDescription: Invalid Lacework account name. Account name may contain alphanumeric characters and dashes only.
  LaceworkAccessKeyID:
    Default: LACEWORK_EA14D831DCC8255D89869D62D323FD0CC60263DED268DFE
    Type: String
    MinLength: '1'
    AllowedPattern: '^[a-zA-Z0-9_]*$'
    ConstraintDescription: Lacework API Access Key ID contains alphanumeric characters and symbols only.
    Description: Lacework API Secret Key ID. See https://support.lacework.com/hc/en-us/articles/360011403853-Generate-API-Access-Keys-and-Tokens
  LaceworkSecretKey:
    Default: _ee5d74f7337b852e9b6b7da637bff89b
    Type: String
    NoEcho: true
    MinLength: '1'
    AllowedPattern: '^[a-zA-Z0-9_]*$'
    ConstraintDescription: Lacework API Secret Key contains alphanumeric characters and symbols only.
    Description: Lacework API Secret Key. See https://support.lacework.com/hc/en-us/articles/360011403853-Generate-API-Access-Keys-and-Tokens
  KeyName:
    Default: ee-default-keypair
    Description: The EC2 Key Pair to allow SSH access to the bastion host.
    Type: AWS::EC2::KeyPair::KeyName

  # advanced
  S3BucketName:
    Type: String
    Default: lacework-alliances
    MinLength: '1'
    Description: "S3 bucket for assets. Use this if you want to customize your deployment. The bucket name can include numbers, lowercase letters, uppercase letters, and hyphens, but it cannot start or end with hyphens (-)."
  S3KeyPrefix:
    Type: String
    Default: awsimmersionday
    MinLength: '1'
    Description: "S3 key prefix for assets directory. Use this if you want to customize your deployment. The prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slashes (/). For more information, see https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html."

Resources:
  BaseVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: >-
        https://lacework-alliances.s3.us-west-2.amazonaws.com/awsimmersionday/templates/setup-vpc.template.yml

  BastionEks:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BaseVpc
    Properties:
      TemplateURL: >-
        https://lacework-alliances.s3.us-west-2.amazonaws.com/awsimmersionday/templates/setup-bastion-eks.template.yml
      Parameters:
        VpcId: !GetAtt BaseVpc.Outputs.VpcId
        PublicSubnetA: !GetAtt BaseVpc.Outputs.PublicSubnetA
        PublicSubnetB: !GetAtt BaseVpc.Outputs.PublicSubnetB
        LaceworkAccountName: !Ref LaceworkAccountName
        LaceworkAccessKeyID: !Ref LaceworkAccessKeyID
        LaceworkSecretKey: !Ref LaceworkSecretKey
        KeyName: !Ref KeyName

  Lacework:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BastionEks
    Properties:
      TemplateURL: >-
        https://lacework-alliances.s3.us-west-2.amazonaws.com/awsimmersionday/templates/setup-lacework.template.yml
      Parameters:
        ResourceNamePrefix: !Ref LaceworkAccountName
        ExternalID: !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]
        CreateTrail: "Yes"

  LaceworkEKSAudit:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BastionEks
    Properties:
      TemplateURL: >-
        https://lacework-alliances.s3.us-west-2.amazonaws.com/awsimmersionday/templates/setup-lacework-eks-audit.template.yml
      Parameters:
        ResourceNamePrefix: !Ref LaceworkAccountName
        ExternalID: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ]

  Pipelines:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - BastionEks
      - LambdaFunctions
    Properties:
      TemplateURL: >-
        https://lacework-alliances.s3.us-west-2.amazonaws.com/awsimmersionday/templates/setup-pipeline.template.yml
      Parameters:
        S3KeyPrefix: !Ref S3KeyPrefix
        LaceworkAccountName: !Ref LaceworkAccountName

  LambdaFunctions:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Lacework
    Properties:
      TemplateURL: >-
        https://lacework-alliances.s3.us-west-2.amazonaws.com/awsimmersionday/templates/setup-lambdas.template.yml
      Parameters:
        LaceworkAccountName: !Ref LaceworkAccountName
        S3BucketName: !Ref S3BucketName
        S3KeyPrefix: !Ref S3KeyPrefix








